name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths: ["airflow_provider_tm1/**/*", "tests/**/*"]

  push:
    branches:
    - main
    paths:
    - "airflow_provider_tm1/**/*"

jobs:

  pytest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: setup python env
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: upgrade pip
        run:
          python -m pip install --upgrade pip

      # is there a better approach to this?
      - name: install airflow-provier-tm1 package
        run:
          pip install .

      - name: install pytest pytest-mock
        run:
          pip install pytest pytest-mock

      - name: run mocked tests
        run: pytest -s -v tests -m "mocked"
